services:
  service:
    depends_on:
      - db
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.goose
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "hackme"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    # command: ["-c", "log_min_messages=debug"]
    ports:
      - 5432:5432
    restart: no
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

volumes:
  postgres_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/grivvus/docker_volumes/postgres/avito_internship
      o: bind
